"use client";

import { createContext, useContext, useState, useEffect, ReactNode, useCallback } from "react";

type Language = "English" | "Hindi" | "Regional";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string, params?: Record<string, string>) => string;
    refreshLanguage: () => Promise<void>;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
    English: {
        "settings.title": "Manage Your Profile & Preferences",
        "settings.subtitle": "Customize your experience, update your info, and control how the Health Assistance Machine interacts with you.",
        "settings.profile": "Your Profile",
        "settings.name": "Name",
        "settings.studentId": "Student ID",
        "settings.registeredNumber": "Registered Number",
        "settings.verifiedOn": "Verified On",
        "settings.language": "Language & Accessibility",
        "settings.preferredLanguage": "Preferred Language",
        "settings.apply": "Apply Changes",
        "settings.notifications": "Notifications & Alerts",
        "settings.privacy": "Privacy & Security",
        "settings.billing": "Billing & Payments",
        "settings.support": "Support & Helpdesk",
        "settings.logout": "Logout Section",
        "settings.logoutBtn": "Log Out Securely",
        "dashboard.back": "Back to Dashboard",
        "dashboard.welcome": "Welcome",
        "dashboard.signedIn": "You're signed in",
        "dashboard.ready": "You're now signed in and ready to use the Smart Health Assistance Machine.",
        "dashboard.choose": "Choose what you want to do :",
        "dashboard.healthAnalysis.title": "Get AI Health Assistance",
        "dashboard.healthAnalysis.desc": "Scan a symptom or wound and describe how you're feeling. Our AI will guide you with safe first-aid steps and suggested items.",
        "dashboard.healthAnalysis.btn": "Start Health Analysis",
        "dashboard.quickBuy.title": "Quick Buy",
        "dashboard.quickBuy.desc": "Need something simple and fast? Bandage, Cotton, Antiseptic, Pain Relief Tablet, OR any available first-aid item.",
        "dashboard.quickBuy.btn": "Buy Directly",
        "dashboard.history.title": "Receipts & History",
        "dashboard.history.desc": "View your past visits, receipts, and items you purchased. (Only minimal masked data is stored.)",
        "dashboard.history.btn": "View My Records",
        "dashboard.settings.title": "Account & Settings",
        "dashboard.settings.desc": "Update your contact number, preferred language, and notifications. Also see the privacy policy & usage limits.",
        "dashboard.settings.btn": "Settings",
        "dashboard.footer.note": "This machine offers basic first aid only. For severe cases, you'll be guided to the nearest medical center.",
        "dashboard.footer.privacy": "Your identity is protected — we only store a secure student token.",
        "welcome.header.title": "CureGenie",
        "welcome.header.subtitle": "Smart Health Assistance",
        "welcome.main.title": "Welcome to CureGenie — the Smart Health Assistance Vending Machine",
        "welcome.main.subtitle": "CureGenie combines intelligent triage, remote clinicians, and ready-to-buy essentials so you can act within seconds.",
        "welcome.btn.getStarted": "Get Started",
        "welcome.btn.preview": "Preview the Flow",
        "welcome.note": "Tap \"Get Started\" to begin. Guidance fee ₹10 for clinician-reviewed recommendations.",
        "welcome.card.safety.title": "For your safety",
        "welcome.card.safety.desc": "This machine provides basic first-aid only. Severe cases are instantly routed to a nearby doctor or hospital.",
        "welcome.card.safety.sub": "Every recommendation is reviewed by remote medical experts. Premium contrast and large tap targets keep the experience accessible.",
        "welcome.card.hub.title": "First-Aid Essentials Hub",
        "welcome.card.hub.desc": "Purchase individual first-aid items instantly — no prescription, no wait.",
        "welcome.essentials.1": "Medical-grade bandages and sterile cotton",
        "welcome.essentials.2": "Antiseptic wipes, gels, and sprays",
        "welcome.essentials.3": "Reusable cold packs and skin-safe tapes",
        "welcome.footer.terms": "Terms & Privacy",
        "welcome.footer.safety": "Safety Info",
        "welcome.footer.contact": "Contact Support",
        "welcome.footer.disclaimer": "Do not use this machine in place of emergency services. For life-threatening situations, call your local emergency number immediately.",
        "preview.title": "Want to see how this machine works?",
        "preview.subtitle": "Get a quick walkthrough before you begin",
        "preview.step1.title": "Authenticate Yourself",
        "preview.step1.desc": "Scan your Student ID to verify your identity securely.",
        "preview.step1.details": "Quick verification takes less than 3 seconds. Your identity is protected with masked tokens.",
        "preview.step2.title": "AI Health Analysis",
        "preview.step2.desc": "Upload a photo and describe your symptoms for safe first-aid guidance.",
        "preview.step2.details": "The AI gives you a step-by-step first-aid instructions tailored to your needs.",
        "preview.step3.title": "View Recommendations",
        "preview.step3.desc": "See AI-assisted first-aid suggestions, severity levels, and recommended items.",
        "preview.step3.details": "Get personalized guidance with confidence indicators and safety alerts for severe cases.",
        "preview.step4.title": "Purchase Items Directly",
        "preview.step4.desc": "Buy essential first-aid items like bandages, antiseptic, and more instantly.",
        "preview.step4.details": "No waiting, no analysis needed. Quick buy option for immediate access to essential items.",
        "preview.step5.title": "Receipt Generation",
        "preview.step5.desc": "Digital receipts are automatically sent to your registered Mail ID.",
        "preview.step5.details": "Keep a record of your purchases and care instructions. Download or print anytime.",
        "preview.btn.prev": "Previous",
        "preview.btn.next": "Next",
        "preview.btn.gotIt": "Got It!",
        "preview.step": "Step",
        "preview.footer": "Your data is never shared during the preview. This is only a demonstration.",
        "dashboard.student": "Student",
        "error.studentNotFound": "Student not found.",
        "error.fetchFailed": "Unable to fetch student name.",
        "auth.barcodeDetected": "Barcode detected",
        "auth.noBarcode": "No barcode detected",
        "payment.upi": "UPI",
        "payment.card": "Card",
        "payment.cash": "Cash",
        "quickbuy.back": "Back to Dashboard",
        "quickbuy.cart": "Cart",
        "quickbuy.title": "What do you need right now?",
        "quickbuy.subtitle": "Pick from the essential first-aid items below. No analysis, no waiting — just select and purchase.",
        "quickbuy.rec.title": "Recommended for You",
        "quickbuy.rec.subtitle": "Based on your last use and common needs",
        "quickbuy.wound.title": "Wound & Injury Care",
        "quickbuy.fever.title": "Fever & Pain Relief",
        "quickbuy.hygiene.title": "Hygiene & Daily Essentials",
        "quickbuy.seasonal.title": "Seasonal Extras",
        "quickbuy.bundles.title": "Bundles & Combos",
        "quickbuy.add": "Add to Cart",
        "quickbuy.buyBundle": "Buy Bundle",
        "quickbuy.stock.low": "Low Stock",
        "quickbuy.stock.left": "Only {count} Left",
        "quickbuy.stock.in": "In Stock",
        "quickbuy.cart.title": "Shopping Cart",
        "quickbuy.cart.empty": "Your cart is empty",
        "quickbuy.cart.total": "Total",
        "quickbuy.cart.checkout": "Proceed to Checkout",
        "quickbuy.cart.payment": "Select Payment Method",
        "quickbuy.cart.complete": "Complete Purchase",
        "quickbuy.footer.1": "OTC medicines only. No prescription drugs are dispensed.",
        "quickbuy.footer.2": "Severe injury? Use 'Health Assistance' for guided help.",
        "quickbuy.footer.3": "Stock updates every 30 minutes.",
        "prod.bandage": "Bandage Pack",
        "prod.cotton": "Cotton Roll",
        "prod.pain": "Instant Pain Relief Tablet",
        "prod.wipes": "Antiseptic Wipes",
        "prod.liquid": "Antiseptic Liquid",
        "prod.gauze": "Sterile Gauze",
        "prod.tape": "Medical Tape",
        "prod.heavy": "Heavy-Duty Bandage",
        "prod.burn": "Burn Relief Gel",
        "prod.joint": "Joint Support Band",
        "prod.para": "Paracetamol (OTC)",
        "prod.ibu": "Ibuprofen 200mg",
        "prod.ors": "Oral Rehydration Salts (ORS Packets)",
        "prod.elec": "Electrolyte Drink Bottle",
        "prod.spray": "Cold/Flu Relief Spray",
        "prod.sani": "Sanitizer Bottle",
        "prod.tissues": "Tissues Pack",
        "prod.wetwipes": "Wet Wipes",
        "prod.pads": "Sanitary Pads",
        "prod.mask": "Disposable Mask",
        "prod.gloves": "Hand Gloves",
        "prod.sun": "Sunscreen Sachet",
        "prod.mosq": "Mosquito Repellent",
        "prod.cream": "Allergic Reaction Cream",
        "prod.balm": "Lip Balm (Dry Weather)",
        "bundle.kit": "First-Aid Mini Kit",
        "bundle.exam": "Exam Stress Pack",
        "bundle.sports": "Sports Kit",
        "bundle.desc.kit": "Bandage + Gauze + Cotton + Antiseptic",
        "bundle.desc.exam": "Electrolyte + Pain Reliever",
        "bundle.desc.sports": "Joint Band + Bandage + Cold Spray",
        "cat.wound": "Wound Care",
        "cat.pain": "Pain Relief",
        "cat.hygiene": "Hygiene",
        "cat.seasonal": "Seasonal",
        "settings.btn.updatePhone": "Update Phone Number",
        "settings.btn.refreshInfo": "Refresh Student Info",
        "settings.notif.desc": "Based on your previous usage, we can notify you about:",
        "settings.notif.list.1": "Receipt deliveries",
        "settings.notif.list.2": "Low-stock alerts for frequently purchased items",
        "settings.notif.list.3": "Health tips based on seasonal changes",
        "settings.notif.list.4": "High-fever or severe-symptom safety warnings",
        "settings.toggle.sms": "SMS Alerts",
        "settings.toggle.email": "Email Receipts",
        "settings.toggle.monthly": "Monthly Usage Summary",
        "settings.toggle.emergency": "Emergency Alerts",
        "settings.privacy.list.1": "We protect your identity using secure student tokens.",
        "settings.privacy.list.2": "No personal medical records are stored",
        "settings.privacy.list.3": "Only masked identity logs are kept for audit safety",
        "settings.privacy.list.4": "You can delete your usage logs anytime",
        "settings.btn.viewData": "View My Data",
        "settings.btn.deleteLogs": "Delete My Logs",
        "settings.btn.privacyPolicy": "Privacy Policy",
        "settings.btn.history": "Transaction History",
        "settings.btn.download": "Download Payment Summary",
        "settings.support.faq": "Frequently Asked Questions",
        "settings.support.emergency": "Emergency Medical Contact",
        "settings.btn.getHelp": "Get Help Now",
        "settings.logout.desc": "For security, you're automatically logged out after inactivity.",
        "history.act.wipes": "Purchased Antiseptic Wipes",
        "history.act.fever": "Bought Fever Relief Tablet",
        "history.act.analysis": "Used AI Health Analysis → Suggested wound care",
        "history.act.bandage": "Purchased Bandage Pack",
        "history.item.bandage": "Bandage",
        "history.item.cotton": "Cotton",
        "history.item.antiseptic": "Antiseptic",
        "history.item.wipes": "Antiseptic Wipes",
        "history.item.fever": "Fever Relief Tablet",
        "history.item.pack": "Bandage Pack",
        "history.item.roll": "Cotton Roll",
        "history.insight.1": "You've used first-aid items 3 times this month.",
        "history.insight.2": "Common purchases: Bandages, Pain Relievers.",
        "history.insight.3": "Tip: Keep a small personal first-aid kit to stay prepared.",
        "history.insight.4": "Your last fever-related item was 5 days ago — stay hydrated!",
        "auth.back": "Back",
        "auth.secure": "Secure Verification",
        "auth.title": "Verify your identity to continue",
        "auth.subtitle": "Scan your Student ID — this helps us to provide you a personalized Experience.",
        "auth.scanner.ready": "Scanner ready",
        "auth.scanner.instruction": "Tap Scan and point your card at the camera",
        "auth.scanner.align": "Align Student ID card here",
        "auth.verifying": "Verifying...",
        "auth.denied": "Camera access blocked. Allow camera in settings or speak with the campus admin.",
        "auth.step1": "Place your Student ID card inside the frame, aligning it with the corner guides.",
        "auth.step2": "Ensure the card is flat and the barcode/ID number is clearly visible.",
        "auth.step3": "Tap \"Capture Image\" to take a photo, then \"Submit for Verification\" to verify your ID.",
        "auth.tips.title": "Helpful tips",
        "auth.tips.1": "If the barcode won't read: Clean the card, increase ambient light, or try rotating the card 90°.",
        "auth.tips.2": "Don't have your card? Contact the campus admin for verification support.",
        "auth.tips.3": "We only store a masked ID token for audit — we don't save your full ID number.",
        "auth.btn.start": "Start Camera",
        "auth.btn.capture": "Capture Image",
        "auth.btn.submit": "Submit for Verification",
        "auth.btn.retake": "Retake Photo",
        "auth.btn.help": "Need help?",
        "auth.msg.requesting": "Requesting camera permission...",
        "auth.msg.captured": "Image captured! Review and submit to verify.",
        "auth.msg.verifying": "Verifying student ID...",
        "auth.msg.success": "Verification Successful!",
        "auth.msg.failed": "Verification Failed",
        "auth.msg.welcome": "Welcome, ",
        "auth.msg.redirect": "Redirecting to dashboard...",
        "auth.msg.tryAgain": "Try Again",
        "history.back": "Back to Dashboard",
        "history.title": "Your Usage History",
        "history.subtitle": "View your recent visits, receipts, and items you purchased from this Health Assistance Machine.",
        "history.search.placeholder": "Search: item name, month, or receipt ID",
        "history.filter.btn": "Filters",
        "history.filter.date": "Filter by Date",
        "history.filter.category": "Filter by Category",
        "history.filter.all": "All",
        "history.filter.today": "Today",
        "history.filter.week": "Week",
        "history.filter.month": "Month",
        "history.filter.medicine": "Medicine",
        "history.filter.firstAid": "First-Aid",
        "history.filter.hygiene": "Hygiene",
        "history.filter.aiAdvice": "AI-Advice",
        "history.recent.title": "Recent Activity",
        "history.recent.subtitle": "Auto-updates every time you use the machine",
        "history.recent.viewAll": "View Full Timeline",
        "history.receipts.title": "Your Digital Receipts",
        "history.receipts.subtitle": "Auto-generated & stored securely (masked identity)",
        "history.receipts.receipt": "Receipt",
        "history.receipts.total": "Total",
        "history.receipts.items": "Items:",
        "history.receipts.payment": "Payment:",
        "history.receipts.sentTo": "Sent To:",
        "history.receipts.download": "Download",
        "history.receipts.print": "Print Copy",
        "history.insights.title": "Smart Insights",
        "history.insights.subtitle": "AI-generated, personalized based on your usage",
        "history.insights.showMore": "Show More Insights",
        "history.insights.showLess": "Show Less Insights",
        "history.download.title": "Download Your Full Log",
        "history.download.subtitle": "Export your entire usage history for records or documentation",
        "history.download.btn": "Download My History (PDF)",
        "history.download.note": "Generated using your masked student token",
        "history.privacy.title": "Privacy Notes",
        "history.privacy.1": "Only masked Student-ID tokens are stored.",
        "history.privacy.2": "No personal medical data is kept — only item purchases and timestamps.",
        "history.privacy.3": "You can request deletion of your stored logs anytime.",
        "history.alerts.downloadReceipt": "Downloading receipt: {receiptId}",
        "analysis.title": "Get AI Health Assistance",
        "analysis.subtitle": "Tell us what's bothering you, we'll guide you safely.",
        "analysis.desc": "Our AI will analyze your symptoms and recommend safe first-aid steps.",
        "analysis.back": "Back to Dashboard",
        "analysis.urgent.title": "Urgent attention recommended",
        "analysis.urgent.desc": "Please seek medical help nearby. This appears to be a serious condition that requires professional medical attention.",
        "analysis.urgent.btn.doctor": "Call Nearby Doctor",
        "analysis.urgent.btn.hospital": "Show Hospital List",
        "analysis.upload.title": "Upload or Capture the Affected Area",
        "analysis.upload.subtitle": "Take a clear photo using the machine camera or upload from your phone",
        "analysis.upload.btn.capture": "Capture Image",
        "analysis.upload.btn.capture.sub": "Use machine camera",
        "analysis.upload.btn.upload": "Upload Image",
        "analysis.upload.btn.upload.sub": "From your device",
        "analysis.upload.tip": "Tip:",
        "analysis.upload.tip.text": "If it's a cut, rash, burn, swelling, or skin irritation — this helps the AI understand it better.",
        "analysis.desc.title": "Add a Description",
        "analysis.desc.subtitle": "Describe your issue in your own words.",
        "analysis.desc.placeholder": "Describe your symptoms… (Optional)",
        "analysis.desc.examples": "Examples you can use:",
        "analysis.desc.ex.1": "Fever since morning, slight headache",
        "analysis.desc.ex.2": "Small cut on finger while using cutter",
        "analysis.desc.ex.3": "Red patches after touching chemicals",
        "analysis.desc.ex.4": "Mild ankle sprain during sports",
        "analysis.btn.analyze": "Analyze My Issue",
        "analysis.btn.analyzing": "Analyzing...",
        "analysis.btn.note": "Takes ~3 seconds. Your data stays private.",
        "analysis.privacy.title": "Privacy Note",
        "analysis.privacy.text": "We don't store your photo. It's analyzed once and deleted immediately. Only a brief summary is kept for your receipt.",
        "analysis.modal.title": "Almost There!",
        "analysis.modal.sub.both": "Please complete the following to analyze your symptoms",
        "analysis.modal.sub.one": "Please complete this requirement to analyze your symptoms",
        "analysis.modal.img.title": "Upload an Image",
        "analysis.modal.img.desc": "Take or upload a clear photo of the affected area",
        "analysis.modal.desc.title": "Describe Your Symptoms",
        "analysis.modal.desc.desc": "Tell us how you're feeling (at least 10 characters)",
        "analysis.modal.btn": "Got it",
        "analysis.modal.note.both": "Both items are required for accurate AI analysis",
        "analysis.modal.note.one": "This item is required for accurate AI analysis",
        "analysis.camera.title": "Capture Photo",
        "analysis.camera.cancel": "Cancel",
        "analysis.camera.capture": "Capture",
    },
    Hindi: {
        "settings.title": "अपनी प्रोफ़ाइल और प्राथमिकताएँ प्रबंधित करें",
        "settings.subtitle": "अपने अनुभव को अनुकूलित करें, अपनी जानकारी अपडेट करें, और नियंत्रित करें कि हेल्थ असिस्टेंस मशीन आपके साथ कैसे इंटरैक्ट करती है।",
        "settings.profile": "आपकी प्रोफ़ाइल",
        "settings.name": "नाम",
        "settings.studentId": "छात्र आईडी",
        "settings.registeredNumber": "पंजीकृत नंबर",
        "settings.verifiedOn": "सत्यापित",
        "settings.language": "भाषा और पहुंच",
        "settings.preferredLanguage": "पसंदीदा भाषा",
        "settings.apply": "परिवर्तन लागू करें",
        "settings.notifications": "सूचनाएं और अलर्ट",
        "settings.privacy": "गोपनीयता और सुरक्षा",
        "settings.billing": "बिलिंग और भुगतान",
        "settings.support": "सहायता और हेल्पडेस्क",
        "settings.logout": "लॉगआउट अनुभाग",
        "settings.logoutBtn": "सुरक्षित रूप से लॉग आउट करें",
        "dashboard.back": "डैशबोर्ड पर वापस जाएं",
        "dashboard.welcome": "स्वागत है",
        "dashboard.signedIn": "आप साइन इन हैं",
        "dashboard.ready": "आप अब साइन इन हैं और स्मार्ट हेल्थ असिस्टेंस मशीन का उपयोग करने के लिए तैयार हैं।",
        "dashboard.choose": "चुनें कि आप क्या करना चाहते हैं:",
        "dashboard.healthAnalysis.title": "AI स्वास्थ्य सहायता प्राप्त करें",
        "dashboard.healthAnalysis.desc": "लक्षण या घाव को स्कैन करें और बताएं कि आप कैसा महसूस कर रहे हैं। हमारा AI आपको सुरक्षित प्राथमिक चिकित्सा चरणों और सुझाए गए आइटमों के साथ मार्गदर्शन करेगा।",
        "dashboard.healthAnalysis.btn": "स्वास्थ्य विश्लेषण शुरू करें",
        "dashboard.quickBuy.title": "त्वरित खरीद",
        "dashboard.quickBuy.desc": "कुछ सरल और तेज़ चाहिए? बैंडेज, कॉटन, एंटीसेप्टिक, दर्द निवारक गोली, या कोई भी उपलब्ध प्राथमिक चिकित्सा आइटम।",
        "dashboard.quickBuy.btn": "सीधे खरीदें",
        "dashboard.history.title": "रसीदें और इतिहास",
        "dashboard.history.desc": "अपनी पिछली यात्राओं, रसीदों और खरीदे गए आइटमों को देखें। (केवल न्यूनतम मास्क्ड डेटा संग्रहीत किया जाता है।)",
        "dashboard.history.btn": "मेरे रिकॉर्ड देखें",
        "dashboard.settings.title": "खाता और सेटिंग्स",
        "dashboard.settings.desc": "अपना संपर्क नंबर, पसंदीदा भाषा और सूचनाएं अपडेट करें। गोपनीयता नीति और उपयोग सीमाएं भी देखें।",
        "dashboard.settings.btn": "सेटिंग्स",
        "dashboard.footer.note": "यह मशीन केवल बुनियादी प्राथमिक चिकित्सा प्रदान करती है। गंभीर मामलों के लिए, आपको निकटतम चिकित्सा केंद्र निर्देशित किया जाएगा।",
        "dashboard.footer.privacy": "आपकी पहचान सुरक्षित है — हम केवल एक सुरक्षित छात्र टोकन संग्रहीत करते हैं।",
        "welcome.header.title": "क्योरजीनी",
        "welcome.header.subtitle": "स्मार्ट स्वास्थ्य सहायता",
        "welcome.main.title": "क्योरजीनी में आपका स्वागत है — स्मार्ट हेल्थ असिस्टेंस वेंडिंग मशीन",
        "welcome.main.subtitle": "क्योरजीनी बुद्धिमान ट्राइएज, दूरस्थ चिकित्सकों और खरीदने के लिए तैयार आवश्यक वस्तुओं को जोड़ती है ताकि आप सेकंड के भीतर कार्य कर सकें।",
        "welcome.btn.getStarted": "शुरू करें",
        "welcome.btn.preview": "प्रवाह का पूर्वावलोकन करें",
        "welcome.note": "शुरू करने के लिए \"शुरू करें\" पर टैप करें। चिकित्सक-समीक्षित सिफारिशों के लिए मार्गदर्शन शुल्क ₹10।",
        "welcome.card.safety.title": "आपकी सुरक्षा के लिए",
        "welcome.card.safety.desc": "यह मशीन केवल बुनियादी प्राथमिक चिकित्सा प्रदान करती है। गंभीर मामलों को तुरंत नजदीकी डॉक्टर या अस्पताल में भेज दिया जाता है।",
        "welcome.card.safety.sub": "हर सिफारिश की समीक्षा दूरस्थ चिकित्सा विशेषज्ञों द्वारा की जाती है। प्रीमियम कंट्रास्ट और बड़े टैप लक्ष्य अनुभव को सुलभ रखते हैं।",
        "welcome.card.hub.title": "प्राथमिक चिकित्सा आवश्यक केंद्र",
        "welcome.card.hub.desc": "व्यक्तिगत प्राथमिक चिकित्सा आइटम तुरंत खरीदें — कोई नुस्खा नहीं, कोई इंतजार नहीं।",
        "welcome.essentials.1": "मेडिकल-ग्रेड बैंडेज और स्टेराइल कॉटन",
        "welcome.essentials.2": "एंटीसेप्टिक वाइप्स, जैल और स्प्रे",
        "welcome.essentials.3": "पुन: प्रयोज्य कोल्ड पैक और त्वचा-सुरक्षित टेप",
        "welcome.footer.terms": "शर्तें और गोपनीयता",
        "welcome.footer.safety": "सुरक्षा जानकारी",
        "welcome.footer.contact": "सहायता से संपर्क करें",
        "welcome.footer.disclaimer": "आपातकालीन सेवाओं के स्थान पर इस मशीन का उपयोग न करें। जीवन के लिए खतरनाक स्थितियों के लिए, तुरंत अपने स्थानीय आपातकालीन नंबर पर कॉल करें।",
        "preview.title": "देखना चाहते हैं कि यह मशीन कैसे काम करती है?",
        "preview.subtitle": "शुरू करने से पहले एक त्वरित पूर्वावलोकन प्राप्त करें",
        "preview.step1.title": "स्वयं को सत्यापित करें",
        "preview.step1.desc": "अपनी पहचान सुरक्षित रूप से सत्यापित करने के लिए अपनी छात्र आईडी स्कैन करें।",
        "preview.step1.details": "त्वरित सत्यापन में 3 सेकंड से भी कम समय लगता है। आपकी पहचान मास्क्ड टोकन के साथ सुरक्षित है।",
        "preview.step2.title": "AI स्वास्थ्य विश्लेषण",
        "preview.step2.desc": "सुरक्षित प्राथमिक चिकित्सा मार्गदर्शन के लिए एक फोटो अपलोड करें और अपने लक्षणों का वर्णन करें।",
        "preview.step2.details": "AI आपको आपकी आवश्यकताओं के अनुरूप चरण-दर-चरण प्राथमिक चिकित्सा निर्देश देता है।",
        "preview.step3.title": "सिफारिशें देखें",
        "preview.step3.desc": "AI-सहायता प्राप्त प्राथमिक चिकित्सा सुझाव, गंभीरता स्तर और अनुशंसित आइटम देखें।",
        "preview.step3.details": "गंभीर मामलों के लिए आत्मविश्वास संकेतकों और सुरक्षा अलर्ट के साथ व्यक्तिगत मार्गदर्शन प्राप्त करें।",
        "preview.step4.title": "सीधे आइटम खरीदें",
        "preview.step4.desc": "बैंदेज, एंटीसेप्टिक और अधिक जैसे आवश्यक प्राथमिक चिकित्सा आइटम तुरंत खरीदें।",
        "preview.step4.details": "कोई इंतजार नहीं, कोई विश्लेषण की आवश्यकता नहीं। आवश्यक वस्तुओं तक तत्काल पहुंच के लिए त्वरित खरीद विकल्प।",
        "preview.step5.title": "रसीद जनरेशन",
        "preview.step5.desc": "डिजिटल रसीदें स्वचालित रूप से आपकी पंजीकृत मेल आईडी पर भेज दी जाती हैं।",
        "preview.step5.details": "अपनी खरीदारी और देखभाल निर्देशों का रिकॉर्ड रखें। किसी भी समय डाउनलोड या प्रिंट करें।",
        "preview.btn.prev": "पिछला",
        "preview.btn.next": "अगला",
        "preview.btn.gotIt": "समझ गया!",
        "preview.step": "चरण",
        "preview.footer": "पूर्वावलोकन के दौरान आपका डेटा कभी साझा नहीं किया जाता है। यह केवल एक प्रदर्शन है।",
        "dashboard.student": "छात्र",
        "error.studentNotFound": "छात्र नहीं मिला।",
        "error.fetchFailed": "छात्र का नाम लाने में असमर्थ।",
        "auth.barcodeDetected": "बारकोड का पता चला",
        "auth.noBarcode": "कोई बारकोड नहीं मिला",
        "payment.upi": "UPI",
        "payment.card": "कार्ड",
        "payment.cash": "नकद",
        "quickbuy.back": "डैशबोर्ड पर वापस जाएं",
        "quickbuy.cart": "कार्ट",
        "quickbuy.title": "आपको अभी क्या चाहिए?",
        "quickbuy.subtitle": "नीचे दी गई आवश्यक प्राथमिक चिकित्सा वस्तुओं में से चुनें। कोई विश्लेषण नहीं, कोई प्रतीक्षा नहीं — बस चुनें और खरीदें।",
        "quickbuy.rec.title": "आपके लिए अनुशंसित",
        "quickbuy.rec.subtitle": "आपके पिछले उपयोग और सामान्य आवश्यकताओं के आधार पर",
        "quickbuy.wound.title": "घाव और चोट की देखभाल",
        "quickbuy.fever.title": "बुखार और दर्द निवारण",
        "quickbuy.hygiene.title": "स्वच्छता और दैनिक आवश्यकताएं",
        "quickbuy.seasonal.title": "मौसमी अतिरिक्त",
        "quickbuy.bundles.title": "बंडल और कॉम्बो",
        "quickbuy.add": "कार्ट में डालें",
        "quickbuy.buyBundle": "बंडल खरीदें",
        "quickbuy.stock.low": "कम स्टॉक",
        "quickbuy.stock.left": "केवल {count} बचे हैं",
        "quickbuy.stock.in": "स्टॉक में है",
        "quickbuy.cart.title": "शॉपिंग कार्ट",
        "quickbuy.cart.empty": "आपकी कार्ट खाली है",
        "quickbuy.cart.total": "कुल",
        "quickbuy.cart.checkout": "चेकआउट के लिए आगे बढ़ें",
        "quickbuy.cart.payment": "भुगतान विधि चुनें",
        "quickbuy.cart.complete": "खरीदारी पूरी करें",
        "quickbuy.footer.1": "केवल OTC दवाएं। कोई प्रिस्क्रिप्शन दवाएं नहीं दी जाती हैं।",
        "quickbuy.footer.2": "गंभीर चोट? निर्देशित मदद के लिए 'स्वास्थ्य सहायता' का उपयोग करें।",
        "quickbuy.footer.3": "स्टॉक हर 30 मिनट में अपडेट होता है।",
        "prod.bandage": "बैंडेज पैक",
        "prod.cotton": "कॉटन रोल",
        "prod.pain": "तत्काल दर्द निवारक गोली",
        "prod.wipes": "एंटीसेप्टिक वाइप्स",
        "prod.liquid": "एंटीसेप्टिक लिक्विड",
        "prod.gauze": "स्टरलाइज़्ड गॉज",
        "prod.tape": "मेडिकल टेप",
        "prod.heavy": "हैवी-ड्यूटी बैंडेज",
        "prod.burn": "बर्न रिलीफ जेल",
        "prod.joint": "जॉइंट सपोर्ट बैंड",
        "prod.para": "पैरासिटामोल (OTC)",
        "prod.ibu": "इबुप्रोफेन 200mg",
        "prod.ors": "ORS पैकेट",
        "prod.elec": "इलेक्ट्रोलाइट ड्रिंक बोतल",
        "prod.spray": "कोल्ड/फ्लू रिलीफ स्प्रे",
        "prod.sani": "सैनिटाइज़र बोतल",
        "prod.tissues": "टिश्यू पैक",
        "prod.wetwipes": "वेट वाइप्स",
        "prod.pads": "सैनिटरी पैड्स",
        "prod.mask": "डिस्पोजेबल मास्क",
        "prod.gloves": "हैंड ग्लव्स",
        "prod.sun": "सनस्क्रीन पाउच",
        "prod.mosq": "मच्छर विकर्षक",
        "prod.cream": "एलर्जिक रिएक्शन क्रीम",
        "prod.balm": "लिप बाम (शुष्क मौसम)",
        "bundle.kit": "फर्स्ट-एड मिनी किट",
        "bundle.exam": "एग्जाम स्ट्रेस पैक",
        "bundle.sports": "स्पोर्ट्स किट",
        "bundle.desc.kit": "बैंडेज + गॉज + कॉटन + एंटीसेप्टिक",
        "bundle.desc.exam": "इलेक्ट्रोलाइट + दर्द निवारक",
        "bundle.desc.sports": "जॉइंट बैंड + बैंडेज + कोल्ड स्प्रे",
        "cat.wound": "घाव देखभाल",
        "cat.pain": "दर्द निवारण",
        "cat.hygiene": "स्वच्छता",
        "cat.seasonal": "मौसमी",
        "settings.btn.updatePhone": "फोन नंबर अपडेट करें",
        "settings.btn.refreshInfo": "छात्र जानकारी ताज़ा करें",
        "settings.notif.desc": "आपके पिछले उपयोग के आधार पर, हम आपको इसके बारे में सूचित कर सकते हैं:",
        "settings.notif.list.1": "रसीद वितरण",
        "settings.notif.list.2": "अक्सर खरीदी जाने वाली वस्तुओं के लिए कम स्टॉक अलर्ट",
        "settings.notif.list.3": "मौसमी बदलावों पर आधारित स्वास्थ्य सुझाव",
        "settings.notif.list.4": "तेज बुखार या गंभीर लक्षणों की सुरक्षा चेतावनी",
        "settings.toggle.sms": "SMS अलर्ट",
        "settings.toggle.email": "ईमेल रसीदें",
        "settings.toggle.monthly": "मासिक उपयोग सारांश",
        "settings.toggle.emergency": "आपातकालीन अलर्ट",
        "settings.privacy.list.1": "हम सुरक्षित छात्र टोकन का उपयोग करके आपकी पहचान की रक्षा करते हैं।",
        "settings.privacy.list.2": "कोई व्यक्तिगत चिकित्सा रिकॉर्ड संग्रहीत नहीं किया जाता है",
        "settings.privacy.list.3": "ऑडिट सुरक्षा के लिए केवल मास्क्ड पहचान लॉग रखे जाते हैं",
        "settings.privacy.list.4": "आप किसी भी समय अपने उपयोग लॉग हटा सकते हैं",
        "settings.btn.viewData": "मेरा डेटा देखें",
        "settings.btn.deleteLogs": "मेरे लॉग हटाएं",
        "settings.btn.privacyPolicy": "गोपनीयता नीति",
        "settings.btn.history": "लेनदेन इतिहास",
        "settings.btn.download": "भुगतान सारांश डाउनलोड करें",
        "settings.support.faq": "अक्सर पूछे जाने वाले प्रश्न",
        "settings.support.emergency": "आपातकालीन चिकित्सा संपर्क",
        "settings.btn.getHelp": "अभी मदद प्राप्त करें",
        "settings.logout.desc": "सुरक्षा के लिए, निष्क्रियता के बाद आप स्वचालित रूप से लॉग आउट हो जाते हैं।",
        "history.act.wipes": "एंटीसेप्टिक वाइप्स खरीदे",
        "history.act.fever": "बुखार राहत की गोली खरीदी",
        "history.act.analysis": "AI स्वास्थ्य विश्लेषण का उपयोग किया → घाव की देखभाल का सुझाव दिया",
        "history.act.bandage": "बैंडेज पैक खरीदा",
        "history.item.bandage": "बैंडेज",
        "history.item.cotton": "कॉटन",
        "history.item.antiseptic": "एंटीसेप्टिक",
        "history.item.wipes": "एंटीसेप्टिक वाइप्स",
        "history.item.fever": "बुखार राहत की गोली",
        "history.item.pack": "बैंडेज पैक",
        "history.item.roll": "कॉटन रोल",
        "history.insight.1": "आपने इस महीने 3 बार प्राथमिक चिकित्सा वस्तुओं का उपयोग किया है।",
        "history.insight.2": "सामान्य खरीदारी: बैंडेज, दर्द निवारक।",
        "history.insight.3": "सुझाव: तैयार रहने के लिए एक छोटी व्यक्तिगत प्राथमिक चिकित्सा किट रखें।",
        "history.insight.4": "आपकी आखिरी बुखार से संबंधित वस्तु 5 दिन पहले थी — हाइड्रेटेड रहें!",
        "auth.back": "वापस",
        "auth.secure": "सुरक्षित सत्यापन",
        "auth.title": "जारी रखने के लिए अपनी पहचान सत्यापित करें",
        "auth.subtitle": "अपनी छात्र आईडी स्कैन करें — यह हमें आपको एक व्यक्तिगत अनुभव प्रदान करने में मदद करता है।",
        "auth.scanner.ready": "स्कैनर तैयार",
        "auth.scanner.instruction": "स्कैन टैप करें और अपने कार्ड को कैमरे की ओर इंगित करें",
        "auth.scanner.align": "छात्र आईडी कार्ड यहां संरेखित करें",
        "auth.verifying": "सत्यापन हो रहा है...",
        "auth.denied": "कैमरा एक्सेस अवरुद्ध। सेटिंग्स में कैमरा की अनुमति दें या कैंपस एडमिन से बात करें।",
        "auth.step1": "अपने छात्र आईडी कार्ड को फ्रेम के अंदर रखें, इसे कोने के गाइड के साथ संरेखित करें।",
        "auth.step2": "सुनिश्चित करें कि कार्ड सपाट है और बारकोड/आईडी नंबर स्पष्ट रूप से दिखाई दे रहा है।",
        "auth.step3": "फोटो लेने के लिए \"इमेज कैप्चर करें\" पर टैप करें, फिर अपनी आईडी सत्यापित करने के लिए \"सत्यापन के लिए जमा करें\" पर टैप करें।",
        "auth.tips.title": "उपयोगी सुझाव",
        "auth.tips.1": "यदि बारकोड नहीं पढ़ा जा रहा है: कार्ड को साफ करें, परिवेशी प्रकाश बढ़ाएं, या कार्ड को 90° घुमाने का प्रयास करें।",
        "auth.tips.2": "क्या आपके पास अपना कार्ड नहीं है? सत्यापन सहायता के लिए कैंपस एडमिन से संपर्क करें।",
        "auth.tips.3": "हम ऑडिट के लिए केवल एक मास्क्ड आईडी टोकन संग्रहीत करते हैं — हम आपका पूरा आईडी नंबर सहेजते नहीं हैं।",
        "auth.btn.start": "कैमरा शुरू करें",
        "auth.btn.capture": "इमेज कैप्चर करें",
        "auth.btn.submit": "सत्यापन के लिए जमा करें",
        "auth.btn.retake": "फोटो फिर से लें",
        "auth.btn.help": "मदद चाहिए?",
        "auth.msg.requesting": "कैमरा अनुमति का अनुरोध किया जा रहा है...",
        "auth.msg.captured": "इमेज कैप्चर हो गई! समीक्षा करें और सत्यापित करने के लिए जमा करें।",
        "auth.msg.verifying": "छात्र आईडी सत्यापित की जा रही है...",
        "auth.msg.success": "सत्यापन सफल!",
        "auth.msg.failed": "सत्यापन विफल",
        "auth.msg.welcome": "स्वागत है, ",
        "auth.msg.redirect": "डैशबोर्ड पर पुनर्निर्देशित किया जा रहा है...",
        "auth.msg.tryAgain": "पुनः प्रयास करें",
        "history.back": "डैशबोर्ड पर वापस जाएं",
        "history.title": "आपका उपयोग इतिहास",
        "history.subtitle": "इस हेल्थ असिस्टेंस मशीन से अपनी हालिया यात्राओं, रसीदों और खरीदे गए आइटमों को देखें।",
        "history.search.placeholder": "खोजें: आइटम का नाम, महीना, या रसीद आईडी",
        "history.filter.btn": "फ़िल्टर",
        "history.filter.date": "तारीख के अनुसार फ़िल्टर करें",
        "history.filter.category": "श्रेणी के अनुसार फ़िल्टर करें",
        "history.filter.all": "सभी",
        "history.filter.today": "आज",
        "history.filter.week": "सप्ताह",
        "history.filter.month": "महीना",
        "history.filter.medicine": "दवा",
        "history.filter.firstAid": "प्राथमिक चिकित्सा",
        "history.filter.hygiene": "स्वच्छता",
        "history.filter.aiAdvice": "AI-सलाह",
        "history.recent.title": "हाल की गतिविधि",
        "history.recent.subtitle": "हर बार जब आप मशीन का उपयोग करते हैं तो ऑटो-अपडेट होता है",
        "history.recent.viewAll": "पूरी समयरेखा देखें",
        "history.receipts.title": "आपकी डिजिटल रसीदें",
        "history.receipts.subtitle": "ऑटो-जेनरेट और सुरक्षित रूप से संग्रहीत (मास्क्ड पहचान)",
        "history.receipts.receipt": "रसीद",
        "history.receipts.total": "कुल",
        "history.receipts.items": "आइटम:",
        "history.receipts.payment": "भुगतान:",
        "history.receipts.sentTo": "को भेजा गया:",
        "history.receipts.download": "डाउनलोड करें",
        "history.receipts.print": "कॉपी प्रिंट करें",
        "history.insights.title": "स्मार्ट इनसाइट्स",
        "history.insights.subtitle": "AI-जनित, आपके उपयोग के आधार पर व्यक्तिगत",
        "history.insights.showMore": "अधिक इनसाइट्स दिखाएं",
        "history.insights.showLess": "कम इनसाइट्स दिखाएं",
        "history.download.title": "अपना पूरा लॉग डाउनलोड करें",
        "history.download.subtitle": "रिकॉर्ड या दस्तावेज़ीकरण के लिए अपना पूरा उपयोग इतिहास निर्यात करें",
        "history.download.btn": "मेरा इतिहास डाउनलोड करें (PDF)",
        "history.download.note": "आपके मास्क्ड छात्र टोकन का उपयोग करके उत्पन्न",
        "history.privacy.title": "गोपनीयता नोट्स",
        "history.privacy.1": "केवल मास्क्ड छात्र-आईडी टोकन संग्रहीत किए जाते हैं।",
        "history.privacy.2": "कोई व्यक्तिगत चिकित्सा डेटा नहीं रखा जाता है — केवल आइटम खरीद और टाइमस्टैम्प।",
        "history.privacy.3": "आप किसी भी समय अपने संग्रहीत लॉग को हटाने का अनुरोध कर सकते हैं।",
        "history.alerts.downloadReceipt": "रसीद डाउनलोड हो रही है: {receiptId}",
        "analysis.title": "AI स्वास्थ्य सहायता प्राप्त करें",
        "analysis.subtitle": "हमें बताएं कि आपको क्या परेशानी है, हम आपको सुरक्षित रूप से मार्गदर्शन करेंगे।",
        "analysis.desc": "हमारा AI आपके लक्षणों का विश्लेषण करेगा और सुरक्षित प्राथमिक चिकित्सा चरणों की सिफारिश करेगा।",
        "analysis.back": "डैशबोर्ड पर वापस जाएं",
        "analysis.urgent.title": "तत्काल ध्यान देने की सिफारिश की गई",
        "analysis.urgent.desc": "कृपया नजदीकी चिकित्सा सहायता लें। यह एक गंभीर स्थिति प्रतीत होती है जिसके लिए पेशेवर चिकित्सा ध्यान देने की आवश्यकता है।",
        "analysis.urgent.btn.doctor": "नजदीकी डॉक्टर को कॉल करें",
        "analysis.urgent.btn.hospital": "अस्पताल सूची दिखाएं",
        "analysis.upload.title": "प्रभावित क्षेत्र को अपलोड या कैप्चर करें",
        "analysis.upload.subtitle": "मशीन कैमरे का उपयोग करके एक स्पष्ट फोटो लें या अपने फोन से अपलोड करें",
        "analysis.upload.btn.capture": "इमेज कैप्चर करें",
        "analysis.upload.btn.capture.sub": "मशीन कैमरे का उपयोग करें",
        "analysis.upload.btn.upload": "इमेज अपलोड करें",
        "analysis.upload.btn.upload.sub": "अपने डिवाइस से",
        "analysis.upload.tip": "सुझाव:",
        "analysis.upload.tip.text": "यदि यह कट, दाने, जलन, सूजन या त्वचा की जलन है — तो यह AI को इसे बेहतर समझने में मदद करता है।",
        "analysis.desc.title": "एक विवरण जोड़ें",
        "analysis.desc.subtitle": "अपनी समस्या का अपने शब्दों में वर्णन करें।",
        "analysis.desc.placeholder": "अपने लक्षणों का वर्णन करें… (वैकल्पिक)",
        "analysis.desc.examples": "उदाहरण जिनका आप उपयोग कर सकते हैं:",
        "analysis.desc.ex.1": "सुबह से बुखार, हल्का सिरदर्द",
        "analysis.desc.ex.2": "कटर का उपयोग करते समय उंगली पर छोटा कट",
        "analysis.desc.ex.3": "रसायनों को छूने के बाद लाल धब्बे",
        "analysis.desc.ex.4": "खेल के दौरान हल्की टखने की मोच",
        "analysis.btn.analyze": "मेरी समस्या का विश्लेषण करें",
        "analysis.btn.analyzing": "विश्लेषण हो रहा है...",
        "analysis.btn.note": "~3 सेकंड लगते हैं। आपका डेटा निजी रहता है।",
        "analysis.privacy.title": "गोपनीयता नोट",
        "analysis.privacy.text": "हम आपकी फोटो स्टोर नहीं करते हैं। इसका एक बार विश्लेषण किया जाता है और तुरंत हटा दिया जाता है। आपकी रसीद के लिए केवल एक संक्षिप्त सारांश रखा जाता है।",
        "analysis.modal.title": "बस हो गया!",
        "analysis.modal.sub.both": "अपने लक्षणों का विश्लेषण करने के लिए कृपया निम्नलिखित पूरा करें",
        "analysis.modal.sub.one": "अपने लक्षणों का विश्लेषण करने के लिए कृपया इस आवश्यकता को पूरा करें",
        "analysis.modal.img.title": "एक इमेज अपलोड करें",
        "analysis.modal.img.desc": "प्रभावित क्षेत्र की स्पष्ट फोटो लें या अपलोड करें",
        "analysis.modal.desc.title": "अपने लक्षणों का वर्णन करें",
        "analysis.modal.desc.desc": "हमें बताएं कि आप कैसा महसूस कर रहे हैं (कम से कम 10 अक्षर)",
        "analysis.modal.btn": "समझ गया",
        "analysis.modal.note.both": "सटीक AI विश्लेषण के लिए दोनों आइटम आवश्यक हैं",
        "analysis.modal.note.one": "सटीक AI विश्लेषण के लिए यह आइटम आवश्यक है",
        "analysis.camera.title": "फोटो कैप्चर करें",
        "analysis.camera.cancel": "रद्द करें",
        "analysis.camera.capture": "कैप्चर करें",
    },
    Regional: {
        "settings.title": "Manage Your Profile & Preferences (Regional)",
        "settings.subtitle": "Customize your experience (Regional Language Placeholder)",
        "settings.profile": "Your Profile",
        "settings.name": "Name",
        "settings.studentId": "Student ID",
        "settings.registeredNumber": "Registered Number",
        "settings.verifiedOn": "Verified On",
        "settings.language": "Language & Accessibility",
        "settings.preferredLanguage": "Preferred Language",
        "settings.apply": "Apply Changes",
        "settings.notifications": "Notifications & Alerts",
        "settings.privacy": "Privacy & Security",
        "settings.billing": "Billing & Payments",
        "settings.support": "Support & Helpdesk",
        "settings.logout": "Logout Section",
        "settings.logoutBtn": "Log Out Securely",
        "dashboard.back": "Back to Dashboard",
        "dashboard.welcome": "Welcome (Regional)",
        "dashboard.signedIn": "You're signed in (Regional)",
        "dashboard.ready": "You're now signed in and ready to use the Smart Health Assistance Machine. (Regional)",
        "dashboard.choose": "Choose what you want to do : (Regional)",
        "dashboard.healthAnalysis.title": "Get AI Health Assistance (Regional)",
        "dashboard.healthAnalysis.desc": "Scan a symptom or wound and describe how you're feeling. (Regional)",
        "dashboard.healthAnalysis.btn": "Start Health Analysis (Regional)",
        "dashboard.quickBuy.title": "Quick Buy (Regional)",
        "dashboard.quickBuy.desc": "Need something simple and fast? (Regional)",
        "dashboard.quickBuy.btn": "Buy Directly (Regional)",
        "dashboard.history.title": "Receipts & History (Regional)",
        "dashboard.history.desc": "View your past visits, receipts, and items you purchased. (Regional)",
        "dashboard.history.btn": "View My Records (Regional)",
        "dashboard.settings.title": "Account & Settings (Regional)",
        "dashboard.settings.desc": "Update your contact number, preferred language, and notifications. (Regional)",
        "dashboard.settings.btn": "Settings (Regional)",
        "dashboard.footer.note": "This machine offers basic first aid only. (Regional)",
        "dashboard.footer.privacy": "Your identity is protected. (Regional)",
    }
};

export function LanguageProvider({ children, forcedLanguage }: { children: ReactNode; forcedLanguage?: Language }) {
    const [language, setLanguageState] = useState<Language>(forcedLanguage || "English");

    const refreshLanguage = useCallback(async () => {
        await new Promise(resolve => setTimeout(resolve, 0));
        // If language is forced (e.g. by route), don't overwrite it with DB/Session data
        if (forcedLanguage) return;

        // Load from session storage
        const storedLang = sessionStorage.getItem("appLanguage") as Language;
        if (storedLang) {
            setLanguageState(storedLang);
        }

        // Fetch from DB if user is logged in
        const uid = sessionStorage.getItem("studentId");
        if (uid) {
            try {
                const res = await fetch(`/api/student-profile/${encodeURIComponent(uid)}`);
                const data = await res.json();
                if (data.success && data.language) {
                    setLanguageState(data.language as Language);
                    sessionStorage.setItem("appLanguage", data.language);
                }
            } catch (err) {
                console.error("Failed to fetch language preference", err);
            }
        }
    }, [forcedLanguage]);

    useEffect(() => {
        // eslint-disable-next-line react-hooks/set-state-in-effect
        refreshLanguage();
    }, [refreshLanguage]);

    const setLanguage = async (lang: Language) => {
        setLanguageState(lang);
        sessionStorage.setItem("appLanguage", lang);

        const uid = sessionStorage.getItem("studentId");
        if (uid) {
            try {
                await fetch("/api/update-language", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ uid, language: lang }),
                });
            } catch (err) {
                console.error("Failed to persist language", err);
            }
        }
    };

    const t = (key: string, params?: Record<string, string>) => {
        let text = translations[language][key] || key;
        if (params) {
            Object.entries(params).forEach(([paramKey, paramValue]) => {
                text = text.replace(`{${paramKey}}`, paramValue);
            });
        }
        return text;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, refreshLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error("useLanguage must be used within LanguageProvider");
    return context;
};
